import { Avatar, Center, Divider, Tag, TagLabel } from '@chakra-ui/react';

import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const About = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center height="50px">
        <nav>
          <Link href="/">
            <a>Home</a>
          </Link>
        </nav>
      </Center>

      <Center height="50px">
        <Divider />
      </Center>

      <main>
        <Center height="50px">
          <h1>Welcome to the About page</h1>
        </Center>
      </main>

      <Center height="50px">
        <Divider />
      </Center>
    </div>
  );
};

export default About;
